language: python
cache:
    directories:
        - $HOME/.cache/pip
python:
  - "3.6"
before_install:
  - pip install nose coverage python-coveralls
install:
  - pip install .[test]
  - pip install indra
script:
  - nosetests gilda -v --with-coverage --cover-inclusive --cover-package=protmapper
after_success:
  - coveralls
